
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { parseCourseName, formatCourseName, isUserAddedCourse } from './utils/course-utils';
import { 
  fetchCourseById, 
  updateCourseWithUserId,
  findCourseByApiId,
  findCourseByName,
  insertCourse,
  getCourseMetadataFromLocalStorage
} from './course/course-queries';

const SUPABASE_URL = "https://rbhzesocmhazynkfyhst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiaHplc29jbWhhenlua2Z5aHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NTcwMDUsImV4cCI6MjA1NjEzMzAwNX0.ckHTv_xaARz6GXc1bWiQ95NleVW2TMaqBzaKzMCiVZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SSR-safe: disable localStorage-based auth persistence during server-side rendering
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    ...(typeof window === 'undefined' ? {
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    } : {}),
  },
});

// Helper function to get the site URL for authentication redirects
export function getSiteUrl(): string {
  if (typeof window !== 'undefined') {
    return window.location.origin;
  }
  return 'http://localhost:5173';
}

// Helper function to log Supabase operations for debugging
export function logSupabaseOperation(operation: string, data: any): void {
  console.log(`[Supabase ${operation}]`, data);
}

// Re-export all necessary functions and utilities
export {
  parseCourseName,
  formatCourseName,
  isUserAddedCourse,
  fetchCourseById,
  updateCourseWithUserId,
  findCourseByApiId,
  findCourseByName,
  insertCourse,
  getCourseMetadataFromLocalStorage
};

// Export type for database errors
export type DatabaseError = {
  code: string;
  details?: string;
  hint?: string;
  message: string;
};
